# Generated by Django 4.1.6 on 2023-02-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='web.tag'),
        ),
    ]
