# Generated by Django 4.1.6 on 2023-03-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_note_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
    ]
